### ISSUE TITLE
Melhorar a apresentação de códigos fonte

### ISSUE THREAD

**Issue by magnunleno** [grupydf/grupydf.github.io#10]
A apresentação de códigos fonte está deixando a desejar.

**Comment by gilsondev** [comment]
Nesse caso seria a edição do README.md?

**Comment by magnunleno** [comment]
Não, tenho que configurar e ativar o pygments pra que os códigos fontes dos artigos fiquem iguais ao do Mind Bending: http://mindbending.org/pt/servindo-sites-estaticos-com-o-nginx

**Comment by gilsondev** [comment]
Ah sim, entendi. Qualquer coisa, se quiser aproveitar, pode usar o colorschemes do tema que criei:

https://github.com/gilsondev/pelican-clean-blog

**Comment by magnunleno** [comment]
That's what I'm talking about...
![pygmetns](https://cloud.githubusercontent.com/assets/353311/8840089/f769b5e2-30b2-11e5-92af-30d372729331.png)

**Comment by magnunleno** [comment]
Closed with commit 20ee09a588294f90ab0b7e416eb7cb3dd122b033

**Comment by gilsondev** [comment]
Nice! ;)
