### ISSUE TITLE
Corrigir a visualização de páginas e artigos em dispositivos mobile

### ISSUE THREAD

**Issue by magnunleno** [grupydf/grupydf.github.io#30]
O padding do conteúdo das páginas e artigos prejudica a leitura em dispositivos mobile.

**Comment by humrochagf** [comment]
Deu uma melhorada boa já, falta só descobrir pq os links grandes não estão quebrando a linha

**Comment by humrochagf** [comment]
vou fechar aqui já que vamos passar a usar o repo do malt

**Comment by magnunleno** [comment]
:+1:
