### ISSUE TITLE
Adicionar Feed

### ISSUE THREAD

**Issue by magnunleno** [grupydf/grupydf.github.io#4]
Adicionar informaçãoes de Feeds RSS e ATOM no site.

**Comment by humrochagf** [comment]
quando adicionar o feed me passa que que eu vou adicionar no planet python

**Comment by magnunleno** [comment]
Feeds implementados no site:
- http://grupydf.github.io/blog/feeds.atom
- http://grupydf.github.io/blog/feeds.rss
