### ISSUE TITLE
[Artigo] Links da Semana #2

### ISSUE THREAD

**Issue by gilsondev** [grupydf/grupydf.github.io#40]
Criar um post com os links comentados pela Internet, Telegram e Slack da comunidade, sobre Python, Software Livre e Tecnologia. Alguns para inserir:
- ~~Python 3 Patterns, Recipes and Idioms: https://python-3-patterns-idioms-test.readthedocs.org/en/latest/~~
- ~~Python and Real-time Web: http://mrjoes.github.io/2013/06/21/python-realtime.html~~
- ~~Utilitário dicio: https://github.com/theuves/dicio~~
- ~~15 Directives to Extend Your Angular.js Apps: http://codecondo.com/angular-js-directives/~~
- ~~PyPi Client: https://github.com/sloria/pypi-cli~~
- ~~Mastering Django (updated to 1.8): https://github.com/big-nige/djangobook-Updated-to-1.8~~
- ~~Awesome Django: https://github.com/rosarior/awesome-django~~
- ~~Tornado WebSockets Assíncrono: https://github.com/arruda/Tornado-WS-Assincrono~~
- ~~Interpolação de Strings: https://www.python.org/dev/peps/pep-0498/~~
- ~~Usando Jinja2 na construção de queries SQL: https://github.com/semirook/snaql~~
- ~~Padrões de Projetos com Python - https://github.com/faif/python-patterns~~
- Palestra do Marco Rougeth sobre Django: http://slides.com/marcorougeth/django-perfeccionistas-prazos

**Comment by gilsondev** [comment]
https://www.python.org/dev/peps/pep-0498/

**Comment by gilsondev** [comment]
Falta somente mandar o link da palestra do Marco Rougeth

**Comment by wagnerjs** [comment]
Fechar esse issue?

**Comment by gilsondev** [comment]
Fechando ;)
