### ISSUE TITLE
Implementar integração contínua

### ISSUE THREAD

**Issue by magnunleno** [grupydf/grupydf.github.io#7]
Implementar integração contínua (TravisCI?) para que o site seja compilado e atualizado a cada commit no branch `pelican`.

**Comment by magnunleno** [comment]
TravisCI integrado! Yay...

![travis-grupydf](https://cloud.githubusercontent.com/assets/353311/8856043/c27bd1f8-313e-11e5-81f8-6a92cb25ac44.png)

**Comment by gilsondev** [comment]
:+1:
